# Get the storage elements use hierarchy

---
- name: Perform Maps module operations on VPLEX
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    cluster_name: "cluster-1"
    # Constant parameters
    verifycert: false
    virt_vol_name: "ansible_virt_vol"
    dist_virt_vol_name: "ansible_distributed_vir_vol"
    dev_name: "ansible_dev"
    dist_dev_name: "ansible_dist_dev"
    extent_name: "ansible_extent"
    strg_vol_name: "ansible_strg_vol"

  collections:
    - dellemc.vplex

  tasks:
    # Get virtual volumes Map
    - name: Get Map - virtual volumes
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        entity_type: 'virtual_volumes'
        entity_name: "{{ virt_vol_name }}"
      register: virt_vol_map
    - debug:
        var: virt_vol_map

    # Get distributed virtual volumes Map
    - name: Get Map - distributed virtual volume
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        entity_type: 'virtual_volumes'
        entity_name: "{{ dist_virt_vol_name }}"
      register: dist_virt_vol_map
    - debug:
        var: dist_virt_vol_map

    # Get devices Map
    - name: Get Map - devices
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        entity_type: 'devices'
        entity_name: "{{ dev_name }}"
      register: dev_map
    - debug:
        var: dev_map

    # Get distributed devices Map
    - name: Get Map - distributed devices
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        entity_type: 'devices'
        entity_name: "{{ dist_dev_name }}"
      register: dist_dev_map
    - debug:
        var: dist_dev_map

    # Get extents Map
    - name: Get Map - extents
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        entity_type: 'extents'
        entity_name: "{{ extent_name }}"
      register: ext_map
    - debug:
        var: ext_map

    # Get storage volumes Map
    - name: Get Map - storage volumes
      dellemc_vplex_maps:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        entity_type: 'storage_volumes'
        entity_name: "{{ strg_vol_name }}"
      register: strg_vol_map
    - debug:
        var: strg_vol_map
