# Manage Ports

---
- name: Manage Ports
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    cluster_name: 'cluster-1'
    port_name: "P0000000046E0124B-A0-FC02"
    # Constant parameters
    verifycert: false

  collections:
    - dellemc.vplex

  tasks:
    # This task gets the port details
    - name: Get port details
      dellemc_vplex_port:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        port_name: "{{ port_name }}"
        state: "present"
      register: get_port

    # Displays the port details
    - debug:
        var: get_port

    # This task Disables a port
    - name: Disable a Port
      dellemc_vplex_port:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        port_name: "{{ port_name }}"
        enabled: false
        state: "present"
      register: disable_port

    # Displays the port details
    - debug:
        var: disable_port

    # This task Disables a port
    - name: Disable a Port - Idempotency
      dellemc_vplex_port:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        port_name: "{{ port_name }}"
        enabled: false
        state: "present"
      register: disable_port_idem

    # Displays the port details
    - debug:
        var: disable_port_idem

    # This task Enables a port
    - name: Enable a Port
      dellemc_vplex_port:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        port_name: "{{ port_name }}"
        enabled: true
        state: "present"
      register: enable_port

    # Displays the port details
    - debug:
        var: enable_port

    # This task Enables a port
    - name: Enable a Port - Idempotency
      dellemc_vplex_port:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        port_name: "{{ port_name }}"
        enabled: true
        state: "present"
      register: enable_port_idem

    # Displays the port details
    - debug:
        var: enable_port_idem
