# Manage Consistency Groups

---
- name: Testing Consistency group operations
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    cluster_name: "cluster-1"
    # Constant parameters
    verifycert: false
    cg_name: "ansible_cg"
    new_cg_name: "ansible_cg_new"
    virtual_volumes: []

  collections:
    - dellemc.vplex

  tasks:

    - name: Build a list of virtual volumes
      set_fact:
        virtual_volumes: "{{ virtual_volumes }} + [ 'ansible_vol_{{ item }}' ]"
      with_sequence: start=1 end=3

    - name: Create Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        state: "present"
      register: create_cg
    - debug:
        var: create_cg

    - name: Create Consistency group - Idempotency
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        state: "present"
      register: create_cg_idem
    - debug:
        var: create_cg_idem

    - name: Add virtual volumes to Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        virtual_volumes: "{{ virtual_volumes }}"
        virtual_volume_state: "present-in-cg"
        state: "present"
      register: add_vol_cg
    - debug:
        var: add_vol_cg

    - name: Add virtual volumes to  Consistency group - Idempotency
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        virtual_volumes: "{{ virtual_volumes }}"
        virtual_volume_state: "present-in-cg"
        state: "present"
      register: add_vol_cg_idem
    - debug:
        var: add_vol_cg_idem

    - name: Get Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        state: "present"
      register: get_cg
    - debug:
        var: get_cg

    - name: Rename Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ cg_name }}"
        new_cg_name: "{{ new_cg_name }}"
        state: "present"
      register: rename_cg
    - debug:
        var: rename_cg

    - name: Rename Consistency group - Idempotency
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ new_cg_name }}"
        new_cg_name: "{{ new_cg_name }}"
        state: "present"
      register: rename_cg_idem
    - debug:
        var: rename_cg_idem

    - name: Remove virtual volumes from Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ new_cg_name }}"
        virtual_volumes: "{{ virtual_volumes }}"
        virtual_volume_state: "absent-in-cg"
        state: "present"
      register: remove_vol_cg
    - debug:
        var: remove_vol_cg

    - name: Remove virtual volumes from Consistency group - Idempotency
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ new_cg_name }}"
        virtual_volumes: "{{ virtual_volumes }}"
        virtual_volume_state: "absent-in-cg"
        state: "present"
      register: remove_vol_cg_idem
    - debug:
        var: remove_vol_cg_idem

    - name: Delete Consistency group
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ new_cg_name }}"
        state: "absent"
      register: delete_cg
    - debug:
        var: delete_cg

    - name: Delete Consistency group - Idempotency
      dellemc_vplex_consistency_group:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        cg_name: "{{ new_cg_name }}"
        state: "absent"
      register: delete_cg_idem
    - debug:
        var: delete_cg_idem
