# Rediscover StorageArray

---
- name: Rediscover StorageArray Tests
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    cluster_name: "cluster-1"
    # Constant parameters
    verifycert: false
    array_name: "array_name"

  collections:
    - dellemc.vplex

  tasks:
    # Get StorageArray
    - name: Get StorageArray
      dellemc_vplex_array:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        array_name: "{{ array_name }}"
      register: StorageArray_details
    - debug:
        var: StorageArray_details

    # Rediscover StorageArray
    - name: Rediscover StorageArray
      dellemc_vplex_array:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        array_name: "{{ array_name }}"
        rediscover: true
      register: Rediscover_StorageArray_details
    - debug:
        var: Rediscover_StorageArray_details
