#  Manage Distributed consistency group

---
- name: Testing Distributed consistency group operations
  hosts: localhost
  connection: local
  vars:
    # variable parameters
    vplexhost: <*****************>
    vplexuser: <*****************>
    vplexpassword: <****************>
    # constant parameters
    verifycert: false
    distributed_cg_name: 'ansible_dr_cg'
    new_distributed_cg_name: 'ansible_dr_cg_name'
    distributed_cg_vv: 'ansible_dr_cg_vol'
    distributed_virtual_volumes: []
    detach_rule: 'cluster-1'
    resume_at: 'cluster-1'

  collections:
    - dellemc.vplex

  tasks:
    - name: Build a list of distributed virtual volumes
      set_fact:
        distributed_virtual_volumes: '{{ distributed_virtual_volumes }} +
        [ ''ansible_dr_vv_{{ item }}'' ]'
      with_sequence: start=1 end=3

    - name: Create a distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        state: 'present'
      register: create_dr_cg
    - debug:
        var: create_dr_cg

    - name: Create a distributed cg - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        state: 'present'
      register: create_dr_cg_idemp
    - debug:
        var: create_dr_cg_idemp

    - name: Get a distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        state: 'present'
      register: get_dr_cg
    - debug:
        var: get_dr_cg

    - name: Add distributed virtual volumes to distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        distributed_virtual_volumes: '{{ distributed_virtual_volumes }}'
        distributed_virtual_volume_state: 'present-in-cg'
        state: 'present'
      register: add_virtual_volumes_to_cg
    - debug:
        var: add_virtual_volumes_to_cg

    - name: Add distributed virtual volumes to distributed cg - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        distributed_virtual_volumes: '{{ distributed_virtual_volumes }}'
        distributed_virtual_volume_state: 'present-in-cg'
        state: 'present'
      register: add_virtual_volumes_to_cg_idemp
    - debug:
        var: add_virtual_volumes_to_cg_idemp

    - name: Remove distributed virtual volumes from distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        distributed_virtual_volumes: '{{ distributed_virtual_volumes }}'
        distributed_virtual_volume_state: 'absent-in-cg'
        state: 'present'
      register: remove_virtual_volumes_from_cg
    - debug:
        var: remove_virtual_volumes_from_cg

    - name: Remove distributed virtual volumes from distributed cg - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        distributed_virtual_volumes: '{{ distributed_virtual_volumes }}'
        distributed_virtual_volume_state: 'absent-in-cg'
        state: 'present'
      register: remove_virtual_volumes_from_cg_idemp
    - debug:
        var: remove_virtual_volumes_from_cg_idemp

    - name: Disable auto-resume-at-loser on distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        auto_resume_at_loser: false
        state: 'present'
      register: disable_dr_cg
    - debug:
        var: disable_dr_cg

    - name: Disable auto-resume-at-loser on distributed cg  - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        auto_resume_at_loser: false
        state: 'present'
      register: disable_dr_cg_idemp
    - debug:
        var: disable_dr_cg_idemp

    - name: Enable auto-resume-at-loser on distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        auto_resume_at_loser: true
        state: 'present'
      register: enable_dr_cg
    - debug:
        var: enable_dr_cg

    - name: Enable auto-resume-at-loser on distributed cg  - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        auto_resume_at_loser: true
        state: 'present'
      register: enable_dr_cg_idemp
    - debug:
        var: enable_dr_cg_idemp

    - name: Update the detach rule of a distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        detach_rule: '{{ detach_rule }}'
        state: 'present'
      register: detach_rule_dr_cg
    - debug:
        var: detach_rule_dr_cg

    - name: Update the detach rule of a distributed cg - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        detach_rule: '{{ detach_rule }}'
        state: 'present'
      register: detach_rule_dr_cg_idemp
    - debug:
        var: detach_rule_dr_cg_idemp

    - name: Resume I/O on vv in distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_vv }}'
        resume_at: '{{ resume_at }}'
        state: 'present'
      register: resume_dr_cg
    - debug:
        var: resume_dr_cg

    - name: Rename a distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ distributed_cg_name }}'
        new_distributed_cg_name: '{{ new_distributed_cg_name }}'
        state: 'present'
      register: rename_cg
    - debug:
        var: rename_cg

    - name: Delete a distributed cg
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ new_distributed_cg_name }}'
        state: 'absent'
      register: delete_distributed_cg
    - debug:
        var: delete_distributed_cg

    - name: Delete a distributed cg - Idempotency
      dellemc_vplex_distributed_consistency_group:
        vplexhost: '{{ vplexhost }}'
        vplexuser: '{{ vplexuser }}'
        vplexpassword: '{{ vplexpassword }}'
        verifycert: '{{ verifycert }}'
        distributed_cg_name: '{{ new_distributed_cg_name }}'
        state: 'absent'
      register: delete_distributed_cg_idemp
    - debug:
        var: delete_distributed_cg_idemp
