# Manage Distributed Virtual Volumes

---
- name: Manage Distributed Virtual Volumes of Vplex
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <************>
    vplexuser: <************>
    vplexpassword: <************>
    verifycert: false
    distributed_dev_name: 'ansible_test_dd_dev'
    distributed_virtvol_id: 'ansible_test_dev'
    distributed_virtvol_name: 'ansible_test_dd_dev_vol'
    thin_enable: true
    expand: true
    # Constant parameters
    new_distributed_vv_name: 'ansible_update_dist_vv'
    new_distributed_vv_name_1: 'ansible_update_dist_vv_id'

  collections:
    - dellemc.vplex

  tasks:
    # Task to create distributed virtual volume
    - name: Create a distributed virtual volume
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ distributed_dev_name }}"
        thin_enable: "{{ thin_enable }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        state: "present"
      register: create_dist_vv
    - debug:
        var: create_dist_vv

    # Task to create distributed virtual volume - Idempotency
    - name: Create a distributed virtual volume - Idempotency
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ distributed_dev_name }}"
        thin_enable: "{{ thin_enable }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        state: "present"
      register: create_dist_vv_idem
    - debug:
        var: create_dist_vv_idem

    # Task to get details of distributed virtual volume by using its name
    - name: Get details of distributed virtual volume by using its name
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        state: "present"
      register: get_dist_vv_name
    - debug:
        var: get_dist_vv_name

    # Task to get details of distributed virtual volume by using its ID
    - name: Get details of distributed virtual volume by using its ID
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        state: "present"
      register: get_dist_vv_id
    - debug:
        var: get_dist_vv_id

    # Task to expand the distributed virtual volume by using its name
    - name: Expand distributed virtual volume by using its name
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        expand: "{{ expand }}"
        state: "present"
      register: expand_dist_vv_name
    - debug:
        var: expand_dist_vv_name

    # Task to expand the distributed virtual volume by using its name
    # - Idempotency
    - name: Expand distributed virtual volume by using its name - Idempotency
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        expand: "{{ expand }}"
        state: "present"
      register: expand_dist_vv_name_idem
    - debug:
        var: expand_dist_vv_name_idem

    # Task to expand the distributed virtual volume by using its ID
    - name: Expand distributed virtual volume by using its ID
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        expand: "{{ expand }}"
        state: "present"
      register: expand_dist_vv_id
    - debug:
        var: expand_dist_vv_id

    # Task to expand the distributed virtual volume by using its ID
    # - Idempotency
    - name: Expand distributed virtual volume by using its ID - Idempotency
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        expand: "{{ expand }}"
        state: "present"
      register: expand_dist_vv_id_idem
    - debug:
        var: expand_dist_vv_id_idem

    # Task to rename the distributed virtual volume by using its name
    - name: Rename distributed virtual volume by using its name
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ distributed_virtvol_name }}"
        new_distributed_virtual_volume_name: "{{ new_distributed_vv_name }}"
        state: "present"
      register: rename_dist_vv_name
    - debug:
        var: rename_dist_vv_name

    # Task to rename the distributed virtual volume by using its ID
    - name: Rename distributed virtual volume by using its ID
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        new_distributed_virtual_volume_name: "{{ new_distributed_vv_name_1 }}"
        state: "present"
      register: rename_dist_vv_id
    - debug:
        var: rename_dist_vv_id

    # Task to rename the distributed virtual volume by using its
    # ID - Idempotency
    - name: Rename distributed virtual volume by using its ID - Idempotency
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        new_distributed_virtual_volume_name: "{{ new_distributed_vv_name_1 }}"
        state: "present"
      register: rename_dist_vv_id_idem
    - debug:
        var: rename_dist_vv_id_idem

    # Task to delete the distributed virtual volume by using its name
    - name: Delete distributed virtual volume by using its name
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ new_distributed_vv_name }}"
        state: "absent"
      register: delete_dist_vv_name
    - debug:
        var: delete_dist_vv_name

    # Task to delete the distributed virtual volume by using its name
    # - Idempotency
    - name: Delete distributed virtual volume by using its name - Idempotency
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_name: "{{ new_distributed_vv_name }}"
        state: "absent"
      register: delete_dist_vv_name_idem
    - debug:
        var: delete_dist_vv_name_idem

    # Task to delete the distributed virtual volume by using its ID
    - name: Delete distributed virtual volume by using its ID
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        state: "absent"
      register: delete_dist_vv_id
    - debug:
        var: delete_dist_vv_id

    # Task to delete the distributed virtual volume by using its ID
    # - Idempotency
    - name: Delete distributed virtual volume by using its ID
      dellemc_vplex_distributed_virtual_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_virtual_volume_id: "{{ distributed_virtvol_id }}"
        state: "absent"
      register: delete_dist_vv_id_idem
    - debug:
        var: delete_dist_vv_id_idem
