# Manage Extents

---
- name: Details of the VPLEX host
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    cluster_name: 'cluster-1'
    storage_volume_id: 'VPD83T3:60000970000197200581533030353332'
    # Constant parameters
    verifycert: false
    extent_name_1: 'ansible_extent_name'
    extent_name_2: 'ansible_extent_ID'
    storage_volume_name: 'Symm0581_0534'
    new_extent_name_1: 'ansible_ext_update_id'
    new_extent_name_2: 'ansible_ext_update_name'

  collections:
    - dellemc.vplex

  tasks:
    # Create an Extent
    - name: Create an Extent with storage volume name
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ extent_name_1 }}"
        storage_volume_name: "{{ storage_volume_name }}"
        state: "present"
      register: create_extent_name

    - debug:
        var: create_extent_name

    # Create an extent
    - name: Create an Extent with storage volume name - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ extent_name_1 }}"
        storage_volume_name: "{{ storage_volume_name }}"
        state: "present"
      register: create_extent_name_idem

    - debug:
        var: create_extent_name_idem

    # Create an Extent
    - name: Create an Extent with storage volume ID
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ extent_name_2 }}"
        storage_volume_id: "{{ storage_volume_id }}"
        state: "present"
      register: create_extent_id

    - debug:
        var: create_extent_id

    # Create an extent
    - name: Create an Extent with storage volume ID - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ extent_name_2 }}"
        storage_volume_id: "{{ storage_volume_id }}"
        state: "present"
      register: create_extent_id_idem

    - debug:
        var: create_extent_id_idem

    # Get an extent
    - name: Get extent details
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ extent_name_1 }}"
        state: "present"
      register: get_extent

    - debug:
        var: get_extent

    # Rename an extent
    - name: Rename Extent using storage volume ID
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_id: "{{ storage_volume_id }}"
        new_extent_name: "{{ new_extent_name_1 }}"
        state: "present"
      register: rename_extent

    - debug:
        var: rename_extent

    # Rename an extent
    - name: Rename Extent using storage volume ID - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_id: "{{ storage_volume_id }}"
        new_extent_name: "{{ new_extent_name_1 }}"
        state: "present"
      register: rename_extent_idem

    - debug:
        var: rename_extent_idem

    # Rename an extent
    - name: Rename Extent using storage volume name
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_name: "{{ storage_volume_name }}"
        new_extent_name: "{{ new_extent_name_2 }}"
        state: "present"
      register: rename_extent_name

    - debug:
        var: rename_extent_name

    # Rename an extent
    - name: Rename Extent using storage volume name - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_name: "{{ storage_volume_name }}"
        new_extent_name: "{{ new_extent_name_2 }}"
        state: "present"
      register: rename_extent_name_idem

    - debug:
        var: rename_extent_name_idem

    # Delete an extent
    - name: Delete an Extent with extent name
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ new_extent_name_1 }}"
        state: "absent"
      register: delete_extent

    - debug:
        var: delete_extent

    # Delete an extent
    - name: Delete an Extent with extent name - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        extent_name: "{{ new_extent_name_1 }}"
        state: "absent"
      register: delete_extent_idem

    - debug:
        var: delete_extent_idem

    # Delete an extent
    - name: Delete an Extent with storage volume name
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_name: "{{ storage_volume_name }}"
        state: "absent"
      register: delete_extent_storagevol_name

    - debug:
        var: delete_extent_storagevol_name

    # Delete an extent
    - name: Delete an Extent with storage volume name - Idempotency
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ cluster_name }}"
        storage_volume_name: "{{ storage_volume_name }}"
        state: "absent"
      register: delete_extent_storagevol_name_idem

    - debug:
        var: delete_extent_storagevol_name_idem
