# Get the storage volumes of size 80G or greater from a specified cluster
---
- name: Get the storage volumes of size 80G or greater from a specified cluster
  hosts: localhost
  connection: local
  vars_files:
    - vars/connection.yml
    - vars/credentials.yml
  vars:
    input: &connection_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
      cluster_name: "{{ cluster_name }}"

  # collections:
  #   - dellemc.vplex

  tasks:
    - name: Get the storage volumes of size 80G or greater
      dellemc_vplex_gatherfacts:
        <<: *connection_vars
        gather_subset:
          - stor_vol
        filters:
          - filter_key: "capacity"
            filter_operator: "lesser"
            filter_value: "80GB"
      register: volume

    # List the storage volume names present in the cluster
    - name: Display storage volumes present in the cluster
      ansible.builtin.debug:
        var: volume
