# Manage distributed device

---
- name: Simple provisioning workflow for VPlex
  hosts: localhost
  connection: local
  vars:
    # Variable parameters
    vplexhost: <**************>
    vplexuser: <**************>
    vplexpassword: <**************>
    # Constant parameters
    verifycert: false
    distributed_device_name: add_test_dd
    source_cluster: cluster-1
    source_device: add_test_1
    target_cluster: cluster-2
    target_device: add_test_2
    rule_set: cluster-1-detaches
    sync: false
    new_distributed_device_name: new_dd_test_name

  # collections:
  # - dellemc.vplex

  tasks:
    - name: Log compatibility message
      ansible.builtin.debug:
        msg: "Distributed Device  playbook is supported in legacy systems VPLEX 6.2 but not supported in VPLEX 7.0 and above version due to device rule-set deprecation."

    - name: List of all storage volumes that are unclaimed in source cluster
      dellemc_vplex_gatherfacts:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ source_cluster }}"
        gather_subset:
          - stor_vol
        filters:
          - filter_key: use
            filter_operator: equal
            filter_value: unclaimed
          - filter_key: capacity
            filter_operator: lesser
            filter_value: 5GB
      register: volume_1

    - name: Claim one Storage Volume in source cluster
      dellemc_vplex_storage_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ source_cluster }}"
        storage_volume_id: "{{ volume_1.StorageVolumes[0] }}"
        claimed_state: claimed
        state: present
      register: volume_claimed_1

    - name: Create extent in source cluster
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ source_cluster }}"
        storage_volume_name: "{{ volume_claimed_1.storage_details.name }}"
        extent_name: extent_{{ volume_claimed_1.storage_details.name.split(':')[-1] }}_1
        state: present
      register: extent_det_1

    - name: Create devices in source cluster
      dellemc_vplex_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ source_cluster }}"
        device_name: "{{ source_device }}"
        extents: "{{ extent_det_1.extent_details.name }}"
        extent_state: present-in-device
        state: present
      register: device_det_1

    - name: List of all storage volumes that are unclaimed in target cluster
      dellemc_vplex_gatherfacts:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ target_cluster }}"
        gather_subset:
          - stor_vol
        filters:
          - filter_key: use
            filter_operator: equal
            filter_value: unclaimed
          - filter_key: capacity
            filter_operator: lesser
            filter_value: 5GB
      register: volume_2

    - name: Claim one Storage Volume in target cluster
      dellemc_vplex_storage_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ target_cluster }}"
        storage_volume_id: "{{ volume_2.StorageVolumes[0] }}"
        claimed_state: claimed
        state: present
      register: volume_claimed_2

    - name: Create extent in target cluster
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ target_cluster }}"
        storage_volume_name: "{{ volume_claimed_2.storage_details.name }}"
        extent_name: extent_{{ volume_claimed_2.storage_details.name.split(':')[-1] }}_1
        state: present
      register: extent_det_2

    - name: Create devices in target cluster
      dellemc_vplex_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ target_cluster }}"
        device_name: "{{ target_device }}"
        extents: "{{ extent_det_2.extent_details.name }}"
        extent_state: present-in-device
        state: present
      register: device_det_2

    # Create a Distributed device
    - name: Create a Distributed device
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ distributed_device_name }}"
        target_cluster: "{{ target_cluster }}"
        target_device: "{{ target_device }}"
        source_cluster: "{{ source_cluster }}"
        source_device: "{{ source_device }}"
        rule_set: "{{ rule_set }}"
        sync: "{{ sync }}"
        state: present
      register: create_dd

    - name: Create_dd
      ansible.builtin.debug:
        var: create_dd

    # Create a Distributed device
    - name: Create a Distributed device - Idempotency
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ distributed_device_name }}"
        target_cluster: "{{ target_cluster }}"
        target_device: "{{ target_device }}"
        source_cluster: "{{ source_cluster }}"
        source_device: "{{ source_device }}"
        rule_set: "{{ rule_set }}"
        sync: "{{ sync }}"
        state: present
      register: create_dd_idem

    - name: Create_dd_idem
      ansible.builtin.debug:
        var: create_dd_idem

    # Rename Distributed device
    - name: Rename Distributed device
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ distributed_device_name }}"
        new_distributed_device_name: "{{ new_distributed_device_name }}"
        state: present
      register: rename_dd

    - name: Rename_dd
      ansible.builtin.debug:
        var: rename_dd

    # Update Rule set name of Distributed device
    - name: Update Rule set name of Distributed device
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        rule_set: cluster-2-detaches
        state: present
      register: rule_set

    - name: Rule_set
      ansible.builtin.debug:
        var: rule_set

    # Update Rule set name of Distributed device
    - name: Update rule set name of distributed_device - Idempotency
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        rule_set: cluster-2-detaches
        state: present
      register: rule_set_idem

    - name: Rule_set_idem
      ansible.builtin.debug:
        var: rule_set_idem

    # Get details of Distributed device
    - name: Get details of Distributed device
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        state: present
      register: get_dd

    - name: Get_dd
      ansible.builtin.debug:
        var: get_dd

    - name: Wait for rebuild
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        state: present
      register: wait_for_rebuild
      until: wait_for_rebuild.dist_device_details.rebuild_status == "done"
      retries: 100
      delay: 5

    # Delete Distributed device
    - name: Delete Distributed device
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        state: absent
      register: delete_dd

    - name: Delete_dd
      ansible.builtin.debug:
        var: delete_dd

    # Delete Distributed device
    - name: Delete Distributed device - Idempotency
      dellemc_vplex_distributed_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        distributed_device_name: "{{ new_distributed_device_name }}"
        state: absent
      register: delete_dd_idem

    - name: Delete_dd_idem
      ansible.builtin.debug:
        var: delete_dd_idem

    - name: Delete devices
      dellemc_vplex_device:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ item.0 }}"
        device_name: "{{ item.1 }}"
        state: absent
      with_together:
        - ["{{ source_cluster }}", "{{ target_cluster }}"]
        - ["{{ source_device }}", "{{ target_device }}"]

    - name: Delete extents
      dellemc_vplex_extent:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ item.0 }}"
        extent_name: "{{ item.1 }}"
        state: absent
      with_together:
        - ["{{ source_cluster }}", "{{ target_cluster }}"]
        - ["{{ extent_det_1.extent_details.name }}", "{{ extent_det_2.extent_details.name }}"]

    - name: Unclaim Storage Volumes
      dellemc_vplex_storage_volume:
        vplexhost: "{{ vplexhost }}"
        vplexuser: "{{ vplexuser }}"
        vplexpassword: "{{ vplexpassword }}"
        verifycert: "{{ verifycert }}"
        cluster_name: "{{ item.0 }}"
        storage_volume_id: "{{ item.1 }}"
        claimed_state: unclaimed
        state: present
      with_together:
        - ["{{ source_cluster }}", "{{ target_cluster }}"]
        - ["{{ volume_claimed_1.storage_details.name }}", "{{ volume_claimed_2.storage_details.name }}"]
