---
# tasks file for createstorageview
- name: Set the variables for create storage view task
  ansible.builtin.set_fact:
    input: &conn_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
      cluster_name: "{{ cluster_name }}"

  collections:
    - dellemc.vplex

- name: "Register Initiator with port_wwn {{createstorageview_init_1_wwn }}"
  dellemc_vplex_initiator:
    <<: *conn_vars
    initiator_name: "{{ createstorageview_init_1_name }}"
    port_wwn: "{{ createstorageview_init_1_wwn }}"
    registered: true
    state: "present"

- name: "Register Initiator with port_wwn {{ createstorageview_init_2_wwn }}"
  dellemc_vplex_initiator:
    <<: *conn_vars
    initiator_name: "{{ createstorageview_init_2_name }}"
    port_wwn: "{{ createstorageview_init_2_wwn }}"
    registered: true
    state: "present"

- name: Set target port variable
  ansible.builtin.set_fact:
    createstorageview_target_port: "{{ createstorageview_feports[0] }}"

- name: Create a storage view and add initiators
  dellemc_vplex_storage_view:
    <<: *conn_vars
    storage_view_name: "{{ createstorageview_storageview_name }}"
    ports: "{{ createstorageview_feports }}"
    initiators: ["{{ createstorageview_init_1_name }}", "{{ createstorageview_init_2_name }}"]
    initiator_state: "present-in-view"
    virtual_volumes: ["{{ item }}"]
    virtual_volume_state: "present-in-view"
    state: "present"
  with_items:
    - "{{ createstorageview_dist_virtual_volume }}"
  register: storage_view
